name: Build NixOS hosts

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ matrix.host }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        host:
          - graphite
          - mercury

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: Build system
        run: >-
          nix build
          ./hosts/${{ matrix.host }}#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
          --no-link
